name: Create OCI Instance
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Run script
        env:
          OCI_USER: ${{ secrets.OCI_USER }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_TENANCY: ${{ secrets.OCI_TENANCY }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_KEY_FILE: ${{ secrets.OCI_KEY_FILE }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
        - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run script
        env:
          OCI_USER: ${{ secrets.OCI_USER }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_TENANCY: ${{ secrets.OCI_TENANCY }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_KEY_FILE: ${{ secrets.OCI_KEY_FILE }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
        - name: Install dependencies
        run: composer install --no-progress --prefer-dist
       - name: Run script
        env:
          OCI_USER: ${{ secrets.OCI_USER }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_TENANCY: ${{ secrets.OCI_TENANCY }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_KEY_FILE: ${{ secrets.OCI_KEY_FILE }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
        run: php index.php
